// ── Supplement seed data ──────────────────────────────────────────────────────
window.HSA = window.HSA || {};

window.HSA.SUPPLEMENTS = [
  {
    id: 'nmn', name: 'NMN', emoji: '⚡', dosage: '500–1000 mg',
    dosageNote: 'Fasted, morning — capsule or sublingual for best absorption',
    rarity: 'rare', category: 'methylation',
    whatItIs: 'A molecule your body uses to make NAD+ — a fuel your cells need to produce energy and repair themselves.',
    whyITakeIt: 'NAD+ declines ~1% per year after 30, impairing mitochondrial function and DNA repair. Taken fasted for maximum absorption. Paired with TMG to prevent SAMe depletion caused by the methylation demand NMN creates.',
    mechanism: 'Your cells use NMN to build NAD+, which is like a rechargeable battery that powers the energy factories inside your cells (mitochondria). NAD+ also helps your cells fix damaged DNA. Levels naturally drop as you age, so supplementing tops them back up.',
    relatedMarkers: [],
    timing: 'Fasted (every day)',
    veganRelevance: 'NAD+ metabolism is equally critical in vegan physiology; NMN is not found in meaningful amounts in plant foods.',
    risks: 'Generally well-tolerated. High doses may increase methylation burden — always pair with TMG. Potential flushing at very high doses.',
    expertNotes: 'The CD38 enzyme rapidly degrades NAD+; Apigenin in the stack specifically inhibits CD38, amplifying NMN\'s effect. NMN vs NR debate: NMN has better recent human bioavailability data.',
    xpValue: 30, unlockLevel: 2
  },
  {
    id: 'nac', name: 'NAC', emoji: '🛡', dosage: '600 mg',
    dosageNote: 'Fasted morning — only on training days (Mon–Fri)',
    rarity: 'uncommon', category: 'liver',
    whatItIs: 'A building block your body uses to make glutathione — your cells\' main defence against damage.',
    whyITakeIt: 'ALT at 67 U/L (elevated, ref <45) signals mild liver stress. NAC is one of the two primary liver-protective supplements in the stack alongside TUDCA. Skipped on rest days to avoid blunting training adaptation signaling from reactive oxygen species.',
    mechanism: 'Your liver uses NAC to produce glutathione, a molecule that neutralises harmful waste products before they can damage cells. Think of glutathione as a cleanup crew — NAC gives the crew the materials it needs to work.',
    relatedMarkers: ['alt', 'ast', 'ggt'],
    timing: 'Fasted, training days only (Mon–Fri)',
    veganRelevance: 'Plant diets tend lower in cysteine-rich foods; NAC closes this gap while directly supporting liver health.',
    risks: 'May blunt some training adaptations if taken on rest days. Avoid if history of seizures. Can cause GI discomfort at high doses.',
    expertNotes: 'The training-day-only protocol is deliberate: ROS from training act as signalling molecules for adaptation. NAC on rest days is purely hepatoprotective without the adaptation-blunting risk.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'tmg', name: 'TMG', emoji: '🔄', dosage: '1000–1500 mg',
    dosageNote: 'Fasted morning, same window as NMN and B12',
    rarity: 'uncommon', category: 'methylation',
    whatItIs: 'A compound found in beets that helps your body process a waste chemical called homocysteine.',
    whyITakeIt: 'Homocysteine at 10.2 µmol/L is borderline high (optimal <9). TMG donates methyl groups to convert homocysteine → methionine. Also protects the SAMe pool depleted by NMN supplementation.',
    mechanism: 'When your body breaks down protein, it produces homocysteine — a chemical that\'s harmful in high amounts. TMG donates a tiny chemical tag that converts homocysteine into a safe, useful amino acid. It\'s basically a recycling step for a potentially dangerous byproduct.',
    relatedMarkers: ['homocysteine', 'folate'],
    timing: 'Fasted (every day)',
    veganRelevance: 'Vegan diets can be lower in betaine (found in beets, spinach, quinoa). TMG ensures consistent methylation support.',
    risks: 'May cause fishy odour at high doses. Generally very safe. Can increase LDL slightly in some people — monitor lipids.',
    expertNotes: 'TMG + B12 + P5P form the methylation triad in this stack. TMG handles one pathway; B12/P5P handle a second. Both are needed to reliably lower homocysteine.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'b12', name: 'Vitamin B12', emoji: '🧬', dosage: '~1000 mcg',
    dosageNote: 'Fasted morning — methylcobalamin or adenosylcobalamin form preferred',
    rarity: 'common', category: 'vegan',
    whatItIs: 'An essential vitamin your nerves, blood cells, and DNA all depend on — and the most important supplement for vegans.',
    whyITakeIt: 'B12 at 530.7 pg/mL — maintained ONLY because of ~1000 mcg/day supplementation. Zero B12 exists in plants; without this, levels would crash toward deficiency within 6–12 months, causing irreversible nerve damage.',
    mechanism: 'B12 helps your body make healthy red blood cells and keeps the protective sheath around your nerves intact. It also helps convert homocysteine (a harmful chemical) into a safe form. Without it, nerve damage and anaemia develop — and there\'s zero B12 in plant foods, so supplementing is non-negotiable.',
    relatedMarkers: ['b12_bm', 'homocysteine', 'folate'],
    timing: 'Fasted (every day)',
    veganRelevance: 'THE most critical vegan supplement. No reliable plant source. Deficiency is the #1 nutritional risk of unfortified vegan diets. Non-negotiable.',
    risks: 'Essentially non-toxic at supplemental doses. Very high doses (>5000 mcg) have been associated with acne in some individuals. Excess is excreted in urine.',
    expertNotes: 'Methylcobalamin is the active form — no conversion step needed. Cyanocobalamin (the cheap form) requires conversion and releases trace cyanide. High-dose supplementation is necessary because B12 absorption is limited — only a tiny amount is absorbed at a time.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'matcha', name: 'Matcha', emoji: '🍵', dosage: 'Standard serving (1–2 tsp)',
    dosageNote: 'Pre-workout — 30–45 min before training',
    rarity: 'common', category: 'training',
    whatItIs: 'Powdered whole green tea leaf — delivers caffeine plus L-theanine for smooth, focused energy without jitters.',
    whyITakeIt: 'Provides clean pre-workout stimulation without coffee\'s anxiety or crash. L-theanine modulates caffeine\'s effect, producing calm focus. EGCG has anti-inflammatory and metabolic benefits. Used Mon–Sat pre-training.',
    mechanism: 'Caffeine blocks adenosine — a chemical in your brain that makes you feel tired — which is why it increases alertness. L-theanine (unique to tea) balances this out, making the energy feel calm rather than anxious. Matcha also contains antioxidants called catechins with mild anti-inflammatory effects.',
    relatedMarkers: ['crp'],
    timing: 'Pre-workout (Mon–Sat, skipped Sunday)',
    veganRelevance: 'Fully plant-based; replaces non-vegan energy options. Has additional anti-inflammatory benefits relevant to borderline CRP.',
    risks: 'Caffeine can impair sleep if taken too late. High doses of matcha may expose to lead (binds in tea leaves). Avoid excess during pregnancy.',
    expertNotes: 'The caffeine:L-theanine ratio in matcha (~1:2) is considered optimal for cognitive performance. Unlike coffee, matcha\'s slower caffeine release avoids the spike-crash cycle.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'citrulline', name: 'Citrulline', emoji: '💪', dosage: '6–8 g',
    dosageNote: 'Pre-workout only — 30–45 min before training on workout days',
    rarity: 'uncommon', category: 'training',
    whatItIs: 'An amino acid that tells your blood vessels to relax and open up, increasing blood flow to your muscles during exercise.',
    whyITakeIt: 'Increases muscle blood flow, reduces training fatigue, and improves pump. Taken pre-training only (skipped rest days). Citrulline is superior to arginine supplementation because it bypasses first-pass liver metabolism.',
    mechanism: 'When you swallow citrulline, your kidneys convert it to arginine, which your blood vessel walls use to make nitric oxide — a gas that signals the muscles in your blood vessel walls to relax and widen. More blood flows through, delivering more oxygen and nutrients to your muscles. More blood flow = better pump and less fatigue.',
    relatedMarkers: [],
    timing: 'Pre-workout, training days only (Mon–Fri, sometimes Sat)',
    veganRelevance: 'Watermelon is a natural source; supplemental form ensures consistent dosing for performance goals.',
    risks: 'Very safe. May cause mild GI discomfort at very high doses. Can lower blood pressure slightly — monitor if already hypotensive.',
    expertNotes: '6 g is the minimum effective dose in studies; 8 g maximises pump and blood flow. Malate form adds malic acid which supports energy production — either form works.',
    xpValue: 15, unlockLevel: 1
  },
  {
    id: 'dutasteride', name: 'Dutasteride', emoji: '💈', dosage: '0.5 mg',
    dosageNote: 'Daily — taken with Lunch, prescription only, requires medical supervision',
    rarity: 'legendary', category: 'hair',
    whatItIs: 'A prescription medication that blocks the enzyme converting testosterone into DHT — the hormone that shrinks hair follicles.',
    whyITakeIt: 'DHT is the primary driver of male pattern hair loss. Dutasteride blocks ~90–95% of DHT conversion (vs finasteride\'s ~70%). By LC/MS/MS (gold standard), my DHT is 7 ng/dL — below the reference range (12–65 ng/dL), confirming very effective 5-AR suppression. Ideal for the hair protocol.',
    mechanism: 'Your body naturally converts some testosterone into a stronger form called DHT. DHT gradually shrinks hair follicles on your scalp until they stop growing hair. Dutasteride blocks this conversion, dramatically reducing DHT levels at the scalp and slowing or stopping hair loss.',
    relatedMarkers: ['dht', 'testosterone', 'shbg'],
    timing: 'Lunch (daily)',
    veganRelevance: '',
    risks: 'Prescription-only. Side effects: reduced libido, erectile dysfunction (rare at 0.5 mg). Half-life is 5 weeks — effects persist long after stopping.',
    expertNotes: 'DHT by LC/MS/MS: 7 ng/dL (LOW, ref 12–65) — dutasteride pushing DHT below the reference floor, confirming maximal 5-AR blockade. The earlier immunoassay reading of 483.7 pg/mL was a method artifact (cross-reactivity with other steroids). Used alongside topical Minoxidil and Copper Peptide for a multi-mechanism hair protocol.',
    xpValue: 40, unlockLevel: 3
  },
  {
    id: 'protein', name: 'Protein Shake', emoji: '🥤', dosage: '~30–40 g per shake',
    dosageNote: 'Post-workout shake — within 30–60 min of training',
    rarity: 'common', category: 'training',
    whatItIs: 'A vegan protein blend (pea + rice) that gives your muscles the amino acids they need to repair and grow after exercise.',
    whyITakeIt: 'Vegan whole foods often fall short of the ~1.6–2.2 g/kg/day protein needed for muscle growth and retention. Post-workout shake closes this gap with fast-digesting amino acids during the recovery window.',
    mechanism: 'After a workout, your muscle fibres have tiny tears in them. Your body repairs and strengthens these tears using amino acids from protein. The shake delivers a concentrated dose quickly — the building blocks your muscles use to rebuild bigger and stronger. Pea + rice together provide all the essential amino acids your body can\'t make itself.',
    relatedMarkers: ['igf1'],
    timing: 'Post-workout (daily)',
    veganRelevance: 'Critical for vegans to meet protein targets. Pea + rice combination provides a complete amino acid profile.',
    risks: 'Generally very safe. Some powders contain heavy metals — use clean-label brands.',
    expertNotes: 'IGF-1 at 146.8 ng/mL is optimal — protein intake and training are maintaining healthy anabolic tone. Pea protein isolate has amino acid scores approaching whey when combined with rice.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'creatine', name: 'Creatine Monohydrate', emoji: '⚗️', dosage: '5 g',
    dosageNote: 'Post-workout shake — can be taken any time of day, timing is flexible',
    rarity: 'uncommon', category: 'training',
    whatItIs: 'The most well-researched performance supplement — helps your muscles recharge faster during intense exercise and supports brain function.',
    whyITakeIt: 'Creatine is found only in animal muscle — a vegan diet provides essentially zero. 5 g/day saturates muscle stores for strength, power, and cognitive function. Note: creatine raises serum creatinine as a lab artefact — my eGFR of 62.2 may partly reflect this, NOT true kidney damage.',
    mechanism: 'During explosive movements like lifting or sprinting, your muscles burn through their main energy currency (ATP) almost instantly. Creatine acts as a rapid energy backup — it donates a phosphate to recharge used-up ATP so your muscles can keep going. It\'s like a turbo boost for short, intense efforts. Vegans see an especially big difference because they start from near-zero.',
    relatedMarkers: ['creatinine', 'egfr'],
    timing: 'Post-workout shake (daily)',
    veganRelevance: 'Essential vegan gap supplement. No plant sources of creatine. Vegans have significantly lower muscle creatine stores at baseline, explaining lower power output until supplemented.',
    risks: 'Extremely safe — 30+ years of research. Raises serum creatinine (lab artefact) — always disclose to clinicians. Can cause water retention. Avoid loading phase if GI sensitive.',
    expertNotes: 'The creatinine/eGFR lab artefact is the most important clinical context in this stack. Creatine → creatinine is a normal metabolic byproduct filtered by kidneys. Higher creatine intake = higher creatinine output = lower calculated eGFR despite normal actual filtration.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'vitd', name: 'Vitamin D3', emoji: '☀️', dosage: '5000 IU',
    dosageNote: 'With post-workout shake (fat-soluble — needs dietary fat for absorption)',
    rarity: 'common', category: 'vegan',
    whatItIs: 'A vitamin your skin makes from sunlight — involved in hundreds of body functions from bone strength to immune defence.',
    whyITakeIt: 'Vitamin D at 136.4 nmol/L — optimal range achieved by 5000 IU daily. Without supplementation at northern latitudes, vegans typically land far below optimal. Near upper range — do NOT increase dose further.',
    mechanism: 'When sunlight hits your skin, it triggers a chemical reaction that starts making vitamin D. Your liver and kidneys then convert it into its active form, which travels through your bloodstream and tells cells in your bones, immune system, and muscles what to do — acting almost like a hormone. Most people don\'t get enough sun to make adequate D3, especially in northern climates.',
    relatedMarkers: ['vitd_bm', 'calcium'],
    timing: 'Post-workout shake (daily, with fat)',
    veganRelevance: 'D3 is traditionally animal-derived (from wool). Vegan D3 from lichen exists — use if strictly vegan. Essential gap for plant-based eaters with limited sun.',
    risks: 'Fat-soluble — accumulates. My level (136.4) is near the top of reference — do not increase. Toxicity causes dangerously high blood calcium.',
    expertNotes: 'Calcium at 2.55 mmol/L is right at the upper limit. This is another signal not to push D3 higher — elevated D3 increases calcium absorption, which is already at ceiling.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'k2', name: 'Vitamin K2', emoji: '🦴', dosage: '100–200 mcg',
    dosageNote: 'With post-workout shake — fat-soluble, always paired with Vitamin D3',
    rarity: 'common', category: 'methylation',
    whatItIs: 'A vitamin that directs calcium into your bones and away from your arteries — the essential partner to Vitamin D3.',
    whyITakeIt: 'Vitamin D3 increases calcium absorption — K2 ensures that calcium goes to bone and not into arterial walls. The D3/K2 pairing is mechanistically essential.',
    mechanism: 'Vitamin D3 increases how much calcium your gut absorbs. That calcium needs to go somewhere. K2 activates two proteins: one that pulls calcium into your bones (making them stronger), and one that actively prevents calcium from depositing in your artery walls. Without K2, extra calcium from D3 supplementation can end up in the wrong places.',
    relatedMarkers: ['vitd_bm', 'calcium'],
    timing: 'Post-workout shake (daily with D3)',
    veganRelevance: 'K2 MK-7 is derived from natto (fermented soy) — vegan-friendly. MK-7 has a longer half-life and is more potent per mcg.',
    risks: 'Very safe. May interact with warfarin/anticoagulants — do not use without medical supervision if on blood thinners.',
    expertNotes: 'The D3+K2 protocol is especially important given Calcium at 2.55 (upper limit). K2 is the safety valve ensuring elevated calcium absorption goes to skeleton, not vasculature.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'fishoil', name: 'Fish Oil', emoji: '🐟', dosage: '~1–2 g EPA/DHA',
    dosageNote: 'Post-workout shake — with fat-containing meal for absorption',
    rarity: 'uncommon', category: 'vegan',
    whatItIs: 'Marine-sourced omega-3 fatty acids — the most potent natural anti-inflammatory compounds you can supplement.',
    whyITakeIt: 'CRP at 1.0 mg/L (borderline inflammation). Rarely eat fish → omega-3 gap is real. EPA and DHA are potent anti-inflammatories. The only non-vegan supplement in the stack — used pragmatically for efficacy.',
    mechanism: 'Your body uses fats to make signalling molecules that control inflammation. Omega-3s (from fish oil) push this system toward anti-inflammatory signals, while omega-6s (found in most vegetable oils) push it toward pro-inflammatory ones. EPA and DHA compete with the pro-inflammatory fats, reducing overall inflammation. They also lower triglycerides and support heart and brain function.',
    relatedMarkers: ['crp', 'triglycerides', 'apo_b'],
    timing: 'Post-workout shake (daily)',
    veganRelevance: 'The key pragmatic exception in the stack. Algae-based DHA+EPA exists (where fish get omega-3s from) — consider switching. ALA from flax converts to EPA/DHA at <5% efficiency in humans.',
    risks: 'High doses (>3 g/day) may increase bleeding time. Can oxidise if not refrigerated — buy fresh, store cold.',
    expertNotes: 'Triglycerides at 0.78 mmol/L are excellent — fish oil is contributing. Apo-B at 89 mg/dL is borderline; omega-3s have strong triglyceride reduction effects.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'taurine', name: 'Taurine', emoji: '❤️', dosage: '1–2 g',
    dosageNote: 'Post-workout shake',
    rarity: 'uncommon', category: 'vegan',
    whatItIs: 'An amino acid found in meat and seafood but absent in plants — important for heart function, liver health, and muscle performance.',
    whyITakeIt: 'Taurine is nearly absent in plants — a genuine vegan gap. Critical for bile production (fat digestion), cardiac rhythm, skeletal muscle performance, and fluid balance. The body makes some but not enough without dietary input.',
    mechanism: 'Taurine does several jobs: it helps your liver produce bile (the fluid that digests fats), it helps regulate how your muscle cells use calcium (needed for contractions), and it acts as an antioxidant. Because there\'s essentially none in plant foods, vegans typically have much lower levels — which is why supplementing matters.',
    relatedMarkers: ['alt', 'ast'],
    timing: 'Post-workout shake (daily)',
    veganRelevance: 'Zero dietary taurine on a plant-based diet. Evidence shows vegans have significantly lower plasma taurine. Critical to supplement.',
    risks: 'Extremely safe even at high doses. No known toxicity.',
    expertNotes: 'Taurine\'s role in bile production is directly relevant given elevated liver enzymes (AST 39, ALT 67) — taurine supports liver bile flow and detoxification pathways alongside NAC and TUDCA.',
    xpValue: 15, unlockLevel: 1
  },
  {
    id: 'fisetin', name: 'Fisetin', emoji: '🍓', dosage: '500 mg',
    dosageNote: 'Pulsed dosing — taken with a fat-containing meal (Sundays and Saturdays typically)',
    rarity: 'rare', category: 'methylation',
    whatItIs: 'A natural plant compound that may help your body clear out old, damaged cells that accumulate as you age.',
    whyITakeIt: 'Senescent cells accumulate with age and release pro-inflammatory signals that accelerate ageing. Fisetin has shown the strongest senolytic activity of tested flavonoids. Taken pulsed (not daily) to match the episodic nature of this clearance process.',
    mechanism: 'As you age, some cells stop working properly but don\'t die — they become "zombie cells." These cells hang around and release chemicals that cause inflammation and damage nearby healthy cells. Fisetin appears to trigger these damaged cells to self-destruct without harming healthy cells. Because this is a cleanup process rather than a daily need, it\'s taken in pulses rather than every day.',
    relatedMarkers: ['crp'],
    timing: 'Lunch, pulse days only (Sun + Sat)',
    veganRelevance: 'Fisetin is found in strawberries, apples, persimmons — but dietary amounts are far below therapeutic doses.',
    risks: 'Limited long-term human data. Generally well-tolerated in short studies.',
    expertNotes: 'Pulsed dosing (2 consecutive days/week) mimics the protocol used in human trials showing senolytic efficacy. Daily dosing is not recommended — senolysis is an episodic process.',
    xpValue: 30, unlockLevel: 2
  },
  {
    id: 'vitc', name: 'Vitamin C', emoji: '🍊', dosage: '500–1000 mg',
    dosageNote: 'Lunch — with food',
    rarity: 'common', category: 'gut',
    whatItIs: 'An essential vitamin your body can\'t make itself — needed for immune defence, collagen production, and absorbing plant-based iron.',
    whyITakeIt: 'CRP at 1.0 (borderline inflammation). Vitamin C enhances plant-iron absorption (important given Iron at 12.3, low-normal on plant-based diet), supports immune function, and regenerates other antioxidants.',
    mechanism: 'Vitamin C does several things at once: it helps your immune cells fight infections, it\'s essential for building collagen (the protein that holds your skin, tendons, and blood vessels together), and it converts plant-based iron into a form your gut can actually absorb. This last point is especially important on a vegan diet, where iron from food is much harder to absorb than iron from meat.',
    relatedMarkers: ['iron', 'crp', 'uibc'],
    timing: 'Lunch (Mon–Fri)',
    veganRelevance: 'Supplemental C specifically taken with iron-rich meals maximises plant-iron absorption — critical for vegan iron status.',
    risks: 'High doses (>2 g/day) can cause GI distress and increase kidney stone risk in susceptible individuals.',
    expertNotes: 'Taking vitamin C with iron-containing meals is more important for vegans than the supplement itself. The iron absorption synergy is the key reason it\'s timed at lunch.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'tongkat', name: 'Tongkat Ali', emoji: '🔥', dosage: '200–400 mg',
    dosageNote: 'Lunch — cycled (Mon, Tue, Thu; skipped Wed, Fri, Sat, Sun)',
    rarity: 'rare', category: 'hormones',
    whatItIs: 'A root extract from Southeast Asia with evidence for freeing up testosterone that\'s being held inactive by a binding protein.',
    whyITakeIt: 'SHBG at 53.42 nmol/L (high-normal) binds free testosterone, reducing bioavailability despite excellent total T of 25.9 nmol/L. Tongkat Ali has evidence for modestly reducing SHBG, increasing free testosterone. Cycled to prevent tolerance.',
    mechanism: 'Most of your testosterone travels through your bloodstream bound to a protein called SHBG. When it\'s bound, it\'s inactive — your cells can\'t use it. Tongkat Ali appears to reduce SHBG levels, freeing up more testosterone to actually reach your cells. It also has stress-reducing effects, which indirectly supports hormone balance.',
    relatedMarkers: ['shbg', 'testosterone', 'free_testosterone', 'cortisol'],
    timing: 'Lunch, cycled (Mon, Tue, Thu)',
    veganRelevance: 'Plant-derived root extract — fully vegan.',
    risks: 'Generally safe. May increase irritability at high doses. Avoid if history of hormone-sensitive cancers. Cycle to avoid tolerance.',
    expertNotes: 'Free T at 8.63 pg/mL is mid-range — has room to optimise given the SHBG picture. Tongkat + Boron are the dual-pronged SHBG strategy.',
    xpValue: 25, unlockLevel: 2
  },
  {
    id: 'tudca', name: 'TUDCA', emoji: '⚗️', dosage: '250–500 mg',
    dosageNote: 'Lunch — same days as NAC (training days: Mon, Tue, Thu)',
    rarity: 'rare', category: 'liver',
    whatItIs: 'A natural bile acid that protects liver cells from damage — especially useful when liver enzymes are elevated.',
    whyITakeIt: 'ALT at 67 U/L and AST at 39 U/L are both elevated — the clearest abnormality in the panel. TUDCA specifically protects liver cells from stress and damage. Cycled with NAC to provide comprehensive liver protection on high-load training days.',
    mechanism: 'Your liver produces bile acids to help digest fats. When these bile acids build up or become too concentrated, they can damage the liver cells that make them. TUDCA is a gentler, water-soluble bile acid that dilutes and displaces the more damaging ones — like replacing harsh cleaning chemicals with gentler ones. It also helps liver cells handle cellular stress better, reducing the chance of cell death.',
    relatedMarkers: ['alt', 'ast', 'ggt', 'bilirubin'],
    timing: 'Lunch, training days only (Mon, Tue, Thu)',
    veganRelevance: 'TUDCA is derived from bear bile traditionally — synthetic versions are available and preferred.',
    risks: 'Very safe. May cause loose stools at high doses. Avoid in complete bile duct obstruction.',
    expertNotes: 'The doctor flagged AST 39 and ALT 67 as the clearest abnormality — likely training/supplement load stress. NAC + TUDCA are specifically chosen for this liver pattern.',
    xpValue: 30, unlockLevel: 2
  },
  {
    id: 'p5p', name: 'P5P', emoji: '🔬', dosage: '25–50 mg',
    dosageNote: 'Lunch — active form of B6, absorbed without conversion',
    rarity: 'uncommon', category: 'methylation',
    whatItIs: 'The ready-to-use active form of Vitamin B6 — a helper molecule your body needs to process homocysteine and make neurotransmitters.',
    whyITakeIt: 'Homocysteine at 10.2 µmol/L is borderline elevated. P5P is the cofactor for the enzyme that converts homocysteine into a safe amino acid. Works alongside B12 and TMG in the methylation triad.',
    mechanism: 'Regular B6 needs to be converted by your liver before your body can use it. P5P skips that step — it\'s already in the active form. Your body uses it as a helper molecule in dozens of chemical reactions, most importantly helping convert homocysteine (a harmful waste chemical) into a useful amino acid. Without enough B6, homocysteine builds up and increases cardiovascular risk.',
    relatedMarkers: ['homocysteine', 'b12_bm'],
    timing: 'Lunch (daily)',
    veganRelevance: 'B6 is abundant in plant foods, but P5P (active form) bypasses conversion steps — more reliable and direct.',
    risks: 'Important: regular B6 above 50 mg/day can cause nerve damage. P5P at 25–50 mg is much safer. Avoid exceeding doses unnecessarily.',
    expertNotes: 'This stack targets both routes for homocysteine clearance — comprehensive homocysteine management using B12, TMG, and P5P together.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'boron', name: 'Boron', emoji: '⚡', dosage: '3–6 mg',
    dosageNote: 'Lunch — with food',
    rarity: 'uncommon', category: 'hormones',
    whatItIs: 'A trace mineral that can modestly lower SHBG — the protein that binds and inactivates testosterone.',
    whyITakeIt: 'SHBG at 53.42 nmol/L is high-normal — reducing it even modestly frees more testosterone. Boron has been shown to reduce SHBG and increase free testosterone in human studies. Works synergistically with Tongkat Ali.',
    mechanism: 'SHBG is a protein your liver makes that latches onto testosterone and carries it through the bloodstream — while it\'s attached, testosterone can\'t enter your cells. Boron appears to reduce how much SHBG your body produces, meaning more testosterone stays in the "free" active form that your cells can actually use.',
    relatedMarkers: ['shbg', 'testosterone', 'free_testosterone'],
    timing: 'Lunch (daily)',
    veganRelevance: 'Found in fruits, nuts, and vegetables — but supplemental amounts for hormonal effects exceed typical dietary intake.',
    risks: 'Very safe at 3–6 mg. Toxicity only at doses hundreds of times higher.',
    expertNotes: 'Boron + Tongkat Ali is the SHBG strategy. Together they address the same goal from different angles. Neither is dramatic alone but they compound.',
    xpValue: 15, unlockLevel: 1
  },
  {
    id: 'magnesium', name: 'Magnesium Glycinate', emoji: '🌙', dosage: '300–400 mg elemental',
    dosageNote: 'Night — 30–60 min before bed',
    rarity: 'common', category: 'neuro',
    whatItIs: 'An essential mineral involved in over 300 reactions in your body — taken at night for muscle relaxation and sleep quality.',
    whyITakeIt: 'Magnesium at 0.85 mmol/L (low-normal). Chronically depleted by stress and intense exercise. Glycinate form is best absorbed and gentlest on the gut. Taken at night for sleep support, muscle relaxation, and calming the nervous system.',
    mechanism: 'Magnesium acts like a natural "off switch" for your nervous system. It blocks overactive receptors in your brain that keep you alert, helping you wind down. In your muscles, it counterbalances calcium — calcium causes contraction, magnesium causes relaxation. Taking it at night supports deeper sleep and helps muscles recover from training.',
    relatedMarkers: ['magnesium_bm'],
    timing: 'Night (daily)',
    veganRelevance: 'Plant foods contain magnesium but compounds called phytates and oxalates reduce absorption. Athletes lose more via sweat. Supplementation is common even on good plant-based diets.',
    risks: 'Very safe. Excess causes loose stools. Glycinate form avoids most GI issues. Avoid oxide form (poorly absorbed, most GI side effects).',
    expertNotes: 'Magnesium deficiency is estimated to affect >50% of Westerners. Serum Mg is a poor indicator of total body status (99% is intracellular) — this level likely understates the true deficit.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'zinc', name: 'Zinc', emoji: '🔩', dosage: '15–30 mg',
    dosageNote: 'Night — taken with magnesium; separate from iron supplements by 2+ hours',
    rarity: 'common', category: 'vegan',
    whatItIs: 'An essential mineral your immune system, wound healing, and testosterone production all depend on — chronically low in vegan diets.',
    whyITakeIt: 'Zinc at 18.3 µmol/L is low-normal. Plant zinc is bound to phytates, reducing absorption by 50–70% vs meat. A classic vegan gap. Zinc supports testosterone synthesis, immune function, and DNA repair.',
    mechanism: 'Zinc is needed by hundreds of different processes in your body. It\'s essential for immune cells to work properly, for wounds to heal, and for testosterone production. Plants contain zinc but also contain phytates — compounds that bind to zinc and prevent your gut from absorbing it. Vegans absorb significantly less zinc per meal than meat-eaters, making supplementation important.',
    relatedMarkers: ['zinc_bm', 'testosterone', 'tsh'],
    timing: 'Night (skipped Wed, Sat, Sun per schedule)',
    veganRelevance: 'The most significant mineral gap in vegan diets after iron. Soaking and fermenting plant foods reduces phytate content. Supplementation is near-universal necessity.',
    risks: 'Excess zinc (>40 mg/day long-term) depletes copper — monitor. Zinc inhibits iron and copper absorption — separate by 2 hours.',
    expertNotes: 'If increasing zinc dose, add copper (1–2 mg) to prevent imbalance. 18.3 µmol/L is at the lower third of normal — there\'s room to optimise.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'ashwagandha', name: 'Ashwagandha', emoji: '🧘', dosage: '300–600 mg',
    dosageNote: 'Night — with magnesium as the calming stack',
    rarity: 'uncommon', category: 'neuro',
    whatItIs: 'An adaptogenic root that helps your body manage stress by lowering cortisol — your main stress hormone.',
    whyITakeIt: 'Cortisol AM at 199.8 nmol/L is mid-range — normal, but ashwagandha helps buffer stress reactivity. Taken at night with magnesium as a synergistic relaxation/recovery stack.',
    mechanism: 'Cortisol is released by your adrenal glands when you\'re stressed — useful short-term but damaging when chronically elevated. Ashwagandha contains active compounds (withanolides) that dial down your brain\'s stress response, resulting in lower cortisol output and a calmer baseline. It also has mild sedative effects through a similar pathway as GABA (your brain\'s main "calm down" chemical), which is why it works well taken at night.',
    relatedMarkers: ['cortisol', 'testosterone'],
    timing: 'Night (Mon, Tue, Thu, Fri — skipped Sun per schedule)',
    veganRelevance: 'Plant-derived. KSM-66 and Sensoril are the standardised, researched extracts to look for.',
    risks: 'May cause GI upset. Rare cases of liver injury at high doses — use standardised extracts. Avoid in pregnancy. May interact with thyroid medications.',
    expertNotes: 'The night-time magnesium + ashwagandha combination is a well-designed recovery stack: Mg reduces nervous system excitation, ashwagandha reduces cortisol — together they support deep sleep quality and muscle recovery.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'glycine', name: 'Glycine', emoji: '💤', dosage: '3–5 g',
    dosageNote: 'Night — 30–60 min before bed',
    rarity: 'common', category: 'methylation',
    whatItIs: 'The simplest amino acid — important for sleep quality, collagen production, and balancing out your other supplements.',
    whyITakeIt: 'Glycine serves multiple roles: (1) sleep — reduces core body temperature and improves sleep quality; (2) collagen precursor; (3) helps build glutathione (your main antioxidant); (4) acts as a brake on the methylation system when NMN and B12 are pushing it hard.',
    mechanism: 'Glycine triggers your body temperature to drop slightly when you take it before bed — and a drop in core temperature is one of the key signals that tells your brain to initiate deep sleep. It\'s also a building block for collagen (the most abundant protein in your body) and glutathione (your main antioxidant). Bonus: it acts as a brake on the methylation system when you\'re taking supplements like NMN and B12 that push it hard.',
    relatedMarkers: [],
    timing: 'Night (daily)',
    veganRelevance: 'Glycine is found in connective tissue (bones, skin, cartilage) — minimally present in plant foods. Supplementation is especially relevant for vegans who don\'t eat collagen-containing animal products.',
    risks: 'Extremely safe. No known toxicity even at high doses.',
    expertNotes: 'The glycine-methylation connection is underappreciated: glycine helps drain excess methyl groups when TMG, NMN, and B12 are all active — preventing hypermethylation.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'apigenin', name: 'Apigenin', emoji: '🌼', dosage: '~50 mg',
    dosageNote: 'Taken with NMN in the fasted morning window, or with first meal',
    rarity: 'uncommon', category: 'neuro',
    whatItIs: 'A plant compound found in chamomile that protects the NAD+ your cells make from being broken down too quickly.',
    whyITakeIt: 'CD38 is the primary NAD+ consumer in the body. Apigenin inhibits CD38, protecting the NAD+ pool that NMN creates. This is the mechanistic synergy: NMN builds NAD+, Apigenin prevents its rapid degradation. Also has mild calming effects.',
    mechanism: 'Your cells constantly produce and use NAD+ (the energy molecule that NMN helps build). But there\'s an enzyme called CD38 that breaks NAD+ down — and it becomes more active as you age. Apigenin blocks this enzyme, so the NAD+ your body makes from NMN lasts longer. Think of it like plugging a drain so the water (NAD+) stays in the tub longer.',
    relatedMarkers: [],
    timing: 'Morning, with NMN (varies per day)',
    veganRelevance: 'Found in chamomile tea, parsley, celery — plant-derived. Supplemental concentrations far exceed dietary amounts.',
    risks: 'Low toxicity profile. May have mild estrogenic activity — avoid high doses if concerned.',
    expertNotes: 'The NMN + Apigenin synergy is the most elegant part of the stack: one builds NAD+, the other blocks its breakdown.',
    xpValue: 25, unlockLevel: 2
  },
  {
    id: 'iodine', name: 'Iodine', emoji: '🫁', dosage: '~150 mcg',
    dosageNote: 'With food — not to be taken with coffee/tea (reduces absorption)',
    rarity: 'common', category: 'vegan',
    whatItIs: 'An essential trace element your thyroid gland uses to make the hormones that control your metabolism.',
    whyITakeIt: 'TSH at 2.92 µIU/mL is normal, but vegan/plant-based diets are consistently low in iodine (no dairy, no seafood). Thyroid function monitoring matters. 150 mcg/day is the recommended daily amount — supplementation ensures sufficiency without excess.',
    mechanism: 'Your thyroid gland — a small butterfly-shaped gland in your neck — makes hormones (T3 and T4) that control how fast your cells burn energy. Every molecule of these hormones contains iodine atoms. Without enough iodine, your thyroid can\'t make enough hormones, your metabolism slows, and you feel fatigued. Your brain then sends stronger and stronger signals to the thyroid to try harder — which is what raises TSH.',
    relatedMarkers: ['tsh', 'free_t3', 'free_t4', 'anti_tpo'],
    timing: 'With food (daily)',
    veganRelevance: 'The most underappreciated vegan gap. Dairy and fish are the primary dietary sources — both absent in vegan diets. Kelp is unreliable. Potassium iodide supplement is the cleanest option.',
    risks: 'Excess iodine (>1000 mcg/day) can actually suppress thyroid function. Do not exceed 150–300 mcg unless medically directed.',
    expertNotes: 'Anti-TPO at 0.24 and Anti-Tg at 2.76 are both very low — thyroid autoimmunity is essentially absent. Reassuring given iodine supplementation.',
    xpValue: 15, unlockLevel: 0
  },
  {
    id: 'garlic', name: 'Garlic', emoji: '🧄', dosage: 'Standard dose (aged extract or 2 fresh cloves equiv.)',
    dosageNote: 'Lunch — with food',
    rarity: 'common', category: 'gut',
    whatItIs: 'A food-as-medicine staple with proven benefits for gut health, inflammation, and cardiovascular health.',
    whyITakeIt: 'CRP at 1.0 mg/L (borderline). Garlic has anti-inflammatory, prebiotic, and cardiovascular effects. Active compounds have antimicrobial effects against harmful gut bacteria while supporting beneficial species. Taken Mon–Fri as part of the gut/inflammation protocol.',
    mechanism: 'When you crush or chop garlic, a reaction produces allicin — a compound with antimicrobial properties that can reduce harmful bacteria in the gut. Garlic also acts as a prebiotic, meaning it feeds the beneficial bacteria in your intestines. On top of that, its compounds help relax blood vessels and have modest anti-inflammatory effects, making it useful for both gut health and heart health.',
    relatedMarkers: ['crp', 'total_chol', 'ldl'],
    timing: 'Lunch (Mon–Fri)',
    veganRelevance: 'Fully plant-based. One of the most powerful functional foods — food as medicine.',
    risks: 'GI distress, heartburn, and bad breath are common. Blood-thinning effect — caution pre-surgery. May interact with anticoagulants.',
    expertNotes: 'Aged garlic extract (AGE) preserves the antioxidant compounds without the GI irritation of raw garlic. Most cardiovascular and anti-inflammatory studies use AGE or standardised preparations.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'ginger', name: 'Ginger', emoji: '🫚', dosage: 'Standard dose (1–2 g extract or fresh equivalent)',
    dosageNote: 'Lunch — with food',
    rarity: 'common', category: 'gut',
    whatItIs: 'A root with potent anti-inflammatory and digestive benefits — a natural alternative to over-the-counter anti-inflammatory drugs.',
    whyITakeIt: 'CRP at 1.0 mg/L (borderline). Ginger\'s active compounds are potent anti-inflammatories. Also improves gastric emptying and motility, supporting nutrient absorption from a high-supplement diet.',
    mechanism: 'Inflammation is partly driven by enzymes that produce inflammatory signalling molecules. Ginger\'s active compounds (gingerols and shogaols) block these enzymes — similar to how ibuprofen works, but gentler and without side effects at normal doses. Ginger also speeds up how quickly food moves through your stomach, which helps with nutrient absorption and digestive comfort.',
    relatedMarkers: ['crp'],
    timing: 'Lunch (Mon–Fri)',
    veganRelevance: 'Fully plant-based. Anti-inflammatory agent that supports the gut lining and microbiome.',
    risks: 'Generally very safe. High doses can increase bleeding risk — caution with anticoagulants. May cause heartburn in sensitive individuals.',
    expertNotes: 'Ginger + garlic + fish oil + fisetin form a multi-mechanism anti-inflammatory layer targeting borderline CRP of 1.0. Together they address inflammation from different angles.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'probiotic', name: 'Probiotic', emoji: '🦠', dosage: 'Per product recommendation',
    dosageNote: 'Lunch — with or just before food for best survival through stomach acid',
    rarity: 'common', category: 'gut',
    whatItIs: 'Live beneficial bacteria that support the ecosystem of microbes living in your gut.',
    whyITakeIt: 'A diverse gut microbiome is a pillar of immune function, inflammation regulation, and even mood. A high supplement load can stress gut flora — probiotics maintain diversity and barrier integrity.',
    mechanism: 'Your gut contains trillions of bacteria — some helpful, some harmful. Probiotics add more of the helpful types. They work by competing with harmful bacteria for space and food, producing compounds that feed the cells lining your gut wall, and communicating with your immune system to keep it calibrated. Think of it as restocking a garden with the plants you want so weeds have less room to take over.',
    relatedMarkers: ['crp'],
    timing: 'Lunch (daily)',
    veganRelevance: 'Vegans often have more diverse microbiomes due to high fibre intake, but supplementation provides targeted strain delivery beyond what diet alone achieves.',
    risks: 'Generally very safe. Avoid in immunocompromised patients without medical guidance. Transient bloating is common in the first 1–2 weeks.',
    expertNotes: 'Strain specificity matters — a multi-strain formula covering both small and large intestine is preferred over single-strain products.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'evoo', name: 'EVOO', emoji: '🫒', dosage: 'Dietary (1–2 tbsp in shake)',
    dosageNote: 'Post-workout shake — fat vehicle for fat-soluble supplements (D3, K2, Fish Oil)',
    rarity: 'common', category: 'gut',
    whatItIs: 'Extra virgin olive oil — the healthiest cooking fat, and the vehicle that helps fat-soluble vitamins actually absorb.',
    whyITakeIt: 'EVOO serves a dual purpose: (1) fat vehicle enabling absorption of Vitamins D3, K2, and fish oil in the shake; (2) oleocanthal in EVOO acts as a natural anti-inflammatory — similar mechanism to ibuprofen. Mediterranean diet data is among the strongest in cardiovascular medicine.',
    mechanism: 'Vitamins D3, K2, and fish oil are all fat-soluble — they dissolve in fat, not water, so they can only be absorbed by your gut if there\'s fat present. Adding EVOO to your shake ensures these supplements actually get absorbed instead of passing through. EVOO itself also contains oleocanthal, a compound that blocks the same inflammatory enzymes that ibuprofen targets.',
    relatedMarkers: ['crp', 'triglycerides', 'hdl'],
    timing: 'Post-workout shake (daily)',
    veganRelevance: 'Fully plant-based. The fat source of choice in the stack — enables fat-soluble vitamin absorption and provides its own anti-inflammatory benefit.',
    risks: 'High calorie density — be mindful of total caloric intake. Quality matters: many "EVOO" products are adulterated with cheaper oils. Buy certified authentic.',
    expertNotes: 'HDL at 1.61 mmol/L is right at the lower optimal boundary — EVOO and fish oil are the primary dietary tools supporting HDL.',
    xpValue: 10, unlockLevel: 0
  },
  {
    id: 'rogaine', name: 'Rogaine / Minoxidil', emoji: '💧', dosage: 'Topical per label (1 mL, 5% solution)',
    dosageNote: 'Topical — applied to scalp twice daily, dry scalp only',
    rarity: 'uncommon', category: 'hair',
    whatItIs: 'A topical medication that increases blood flow to hair follicles — the most evidence-backed topical treatment for hair loss.',
    whyITakeIt: 'Increases blood flow and nutrient delivery to hair follicles, extending the growth phase. Works synergistically with Dutasteride (DHT block) and Copper Peptide (follicle stimulation). Three-mechanism hair protocol.',
    mechanism: 'Hair follicles need a steady supply of blood to function. Minoxidil works by opening up the small blood vessels that supply the scalp, increasing circulation to follicles that have been getting progressively less blood. More blood flow delivers more nutrients and oxygen, keeping follicles active for longer. It doesn\'t address the DHT cause of hair loss — that\'s what Dutasteride handles.',
    relatedMarkers: ['dht'],
    timing: 'Topical, applied to scalp 2x daily (separate from supplement schedule)',
    veganRelevance: '',
    risks: 'Scalp irritation, unwanted facial hair if product transfers. Shedding in first 4–8 weeks is normal. Do not apply to broken skin.',
    expertNotes: 'The "minoxidil shed" in weeks 4–8 is normal — follicles synchronise into growth phase simultaneously. Stopping treatment causes reversion within 3–6 months.',
    xpValue: 20, unlockLevel: 1
  },
  {
    id: 'copper_peptide', name: 'Copper Peptide Serum', emoji: '🧴', dosage: 'Topical per label',
    dosageNote: 'Topical — applied to scalp, typically at night after Rogaine has dried',
    rarity: 'uncommon', category: 'hair',
    whatItIs: 'A topical serum containing a naturally occurring copper compound that activates growth signals in hair follicles.',
    whyITakeIt: 'Third pillar of the hair protocol alongside Dutasteride (DHT block) and Minoxidil (blood flow). GHK-Cu stimulates follicle proliferation, promotes blood vessel growth around follicles, and has anti-inflammatory effects on the scalp.',
    mechanism: 'GHK-Cu (the active compound) mimics signals your body uses to trigger tissue repair. When applied to the scalp, it activates stem cells in the base of each hair follicle, encouraging them to produce new hair growth. It also promotes new blood vessel formation around follicles and reduces inflammation in the scalp that can suppress follicle activity.',
    relatedMarkers: ['dht'],
    timing: 'Topical, nighttime scalp application',
    veganRelevance: 'GHK-Cu is synthetic — vegan-compatible.',
    risks: 'Generally well-tolerated topically. Patch test recommended.',
    expertNotes: 'The three-pronged hair protocol: Dutasteride (blocks DHT production), Minoxidil (increases blood flow), Copper Peptide (promotes follicle growth). Each targets a different failure point in hair loss.',
    xpValue: 20, unlockLevel: 1
  }
];
